# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"
gem 'colorize', '~> 0.8.1'
gem 'date', '~> 3.2', '>= 3.2.2'
gem 'rspec', '~> 3.11'
gem 'tty-prompt', '~> 0.23.1'
gem 'tty-table', '~> 0.12.0'
gem 'tty-box', '~> 0.7.0'
gem 'tty-markdown', '~> 0.7.0'